---

- name: install IUS release package
  yum:
    name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Ensure PHP-FPM is installed from IUS
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "php{{php_vers}}-fpm"
    - "php{{php_vers}}-devel"

#- name: debug the variable
#  debug:
#    var: phpfpm_max_children


- name: Add php-fpm user to app group
  user:
   name: php-fpm
   groups: "{{ app | default(omit, true) }}"
   shell: /usr/sbin/nologin
   

- name: Ensure pool config is in place
  template:
    src: www.conf.j2
    dest: "{{phpfpm_path}}/www.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Ensure PHP-FPM service is restarted to enable new config
  systemd:
    name: php-fpm
    state: restarted
    enabled: yes
#    
#- name: Configure OpCache
#  include: configure_opcache.yml