---

- name: Run lamp tasks
  hosts: all
  become: yes
  vars_files:
    - defaults.yml

  roles:
    - common 
    - mariadb
    - redis
    - php-fpm
    - openssl
#    - apache
    - httpd
#    - apache-no-varnish