---

- import_playbook: lamp.yml
  vars: 
    app: magento


- name: Ensure LAMP is installed
  hosts: all
  become: yes
  vars: 
   app: magento
  vars_files:
   - defaults.yml
  roles:
    - common 
    - magento
    - iptables