---

- import_playbook: lamp.yml
  vars: 
    app: wordpress


- name: Ensure LAMP is installed
  hosts: all
  become: yes
  vars: 
   app: wordpress
  vars_files:
   - defaults.yml
  roles:
    - common 
#    - wordpress
#    - iptables