---

- name: Ensure wordpress dependencies are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
     - php-zip
     - php-mysql
     - php-redis
  notify: 
    - Restart PHP-FPM

- name: Assign random password for wordpress admin user
  set_fact:
    wordpress_admin_password: "{{ lookup('password', '~/wordpress_admin_password length=24')}}"

- name: check if wp-cli has been installed
  command: 'stat /usr/local/bin/wp'
  register: wpcli_installed
  ignore_errors: yes

- name: install wp-cli
#  command: 'wget -O /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; chmod +x /usr/local/bin/wp'
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: '0777'
    owner: root
    group: root
  when: wpcli_installed is failed

- name: check whether wordpress has been downloaded
  command: 'stat {{ app_path }}/wp-settings.php'
  register: wp_installed
  ignore_errors: yes
  
- name: install wp core
  command: "{{ item }}"
  when: wp_installed is failed
  loop:
    - "wp core download --allow-root --path={{ app_path }}"
    - >
      wp config create --allow-root --dbname={{ app }}  --dbuser={{ app }}
      --dbpass="{{ app_db_password }}" --path={{ app_path }}
    - >
      wp core install --allow-root --url={{ my_pub_ip4 }} --title="Wordpress SpinUp"
      --admin_user=wpadmin --admin_password="{{ wordpress_admin_password }}"
      --admin_email=none@example.com  --path={{ app_path }}
  
- name: check for wp-redis plugin installation
  command: "wp plugin list --allow-root | grep wp-redis"
  register: wpredis_installed
  ignore_errors: yes
  
- name: download and install wp_redis plugin
  git: 
    repo: "https://github.com/pantheon-systems/wp-redis"
    dest: "{{ app_path }}/wp-content/plugins/wp-redis"
  when: wpredis_installed is failed
  
- name: activate wp_redis plugin
  command: "{{ item }}"
  when: wpredis_installed is failed
  loop:
    - "wp plugin activate --allow-root wp-redis --path={{ app_path }}"
    - "wp redis enable --allow-root --path={{ app_path }}"
  
- name: Ensure web directories have correct owner, group, and mode
  file:
    state: directory
    recurse: yes
    owner: "{{ app }}"
    group: "{{ web_group }}"
    path: "{{ app_path }}"
    mode: 'u=rwX,g=rwX,o=---'
    
  
  
  
  
  