- name: start apache
  service:
    name: httpd
    state: started

- name: reload apache
  service:
    name: httpd
    state: reloaded

- name: restart apache
  service:
    name: httpd
    state: restarted