---
- name: install IUS release package
  yum:
    name: "https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm"
    state: present
  when: ansible_os_family == 'RedHat'


- name: Ensure mariadb packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "mariadb{{ mariadb_vers }}-server"
    - MySQL-python

- name: Ensure MariaDB is enabled and starts on boot
  systemd:
    name: mariadb
    state: started
    enabled: yes
   

- name: Assign random password for MySQL root user
  set_fact:
    mysql_root_pw: "{{ lookup('password', '~/mysql_root_pw chars=ascii_letters,digits length=36')}}"

- name: Set root password
  block:
    - mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_pw }}"
        state: present
  rescue:
    - template: 
        src: my.cnf.j2 
        dest: /root/.my.cnf 
        owner: root
        group: root 
        mode: 0600


- name: Remove anonymous users a la mysql_secure_installation
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Remove test db
  mysql_db:
    name: test
    state: absent

- name: Create app database
  mysql_db:
    name: "{{ app }}"
    state: present
#
#- name: Assign random password for app database user
#  set_fact:
#    app_db_password: "{{ lookup('password', '~/app_db_password chars=ascii_letters,digits length=36')}}"
#
#- name: Ensure app database user is present with proper permissions
#  mysql_user:
#    login_user: root
#    check_implicit_admin: yes
#    name: "{{ app }}"
#    password: "{{ app_db_password }}"
#    priv: "{{ app }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES,EXECUTE,CREATE VIEW,SHOW VIEW,CREATE ROUTINE,ALTER ROUTINE,TRIGGER"
#    host: localhost
#    update_password: on_create
#
#- name: Tune system for MariaDB
#  include: system_tuning.yml
#  when: mysql_system_tuning