---

- name: Ensure optimized mariadb config is active
  template:
    src: mariadb-server.cnf.j2
    dest: "{{ mariadb_config_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart mariadb
