---

- name: Generate an OpenSSL private key
  openssl_privatekey:
    path: "{{ssl_path}}/private/{{ app }}.key"

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{ ssl_path }}/certs/{{ app }}.csr"
    privatekey_path: "{{ ssl_path }}/private/{{ app }}.key"
    common_name: "{{ app }}.example.com"

- name: Generate self-signed SSL certificate
  openssl_certificate:
    path: "{{ ssl_path }}/certs/{{ app }}.crt"
    privatekey_path: "{{ ssl_path }}/private/{{ app }}.key"
    provider: selfsigned
    csr_path: "{{ ssl_path }}/certs/{{ app }}.csr"
    